### ISSUE TITLE
Compile failure on SBCL 2.0.6

### ISSUE THREAD

**Issue by equwal** [melisgl/named-readtables#20] opened 2020-07-28 03:38 UTC
Backtrace:
```
* (ql:quickload :named-readtables)
To load "named-readtables":
  Load 1 ASDF system:
    asdf
  Install 1 Quicklisp release:
    named-readtables
; Loading "named-readtables"
[package editor-hints.named-readtables]...........
[package editor-hints.named-readtables]........
debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {10009F0083}>:
  The value
    0
  is not of type
    LIST

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [TRY-RECOMPILING              ] Recompile named-readtables and try loading it again
  1: [RETRY                        ] Retry loading FASL for
   #<NAMED-READTABLES-SOURCE-FILE "named-readtables" "named-readtables">.
  2: [ACCEPT                       ] Continue, treating loading FASL for
   #<NAMED-READTABLES-SOURCE-FILE "named-readtables" "named-readtables">
                                     as having been successful.
  3:                                 Retry ASDF operation.
  4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  5:                                 Retry ASDF operation.
  6:                                 Retry ASDF operation after resetting the
                                     configuration.
  7: [ABORT                        ] Give up on "named-readtables"
  8:                                 Exit debugger, returning to top level.


debugger invoked on a UNDEFINED-FUNCTION in thread #<THREAD "main thread" RUNNING {10009F0083}>: The function EDITOR-HINTS.NAMED-READTABLES:READTABLE-NAME is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE                     ] Retry calling READTABLE-NAME.
  1: [USE-VALUE                    ] Call specified function.
  2: [RETURN-VALUE                 ] Return specified values.
  3: [RETURN-NOTHING               ] Return zero values.
  4: [TRY-RECOMPILING              ] Recompile named-readtables and try loading it again
  5: [RETRY                        ] Retry loading FASL for #<NAMED-READTABLES-SOURCE-FILE "named-readtables" "named-readtables">.
  6: [ACCEPT                       ] Continue, treating loading FASL for #<NAMED-READTABLES-SOURCE-FILE "named-readtables" "named-readtables"> as having been successful.
  7:                                 Retry ASDF operation.
  8: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
  9:                                 Retry ASDF operation.
 10:                                 Retry ASDF operation after resetting the configuration.
 11: [ABORT                        ] Give up on "named-readtables"
 12:                                 Exit debugger, returning to top level.

("undefined function" #<error printing READTABLE {100F6DEEC3}>)
```

My SBCL
```
$ sbcl --version
SBCL 2.0.6
```

**Comment by melisgl** [comment] 2020-07-28 07:30
Duplicate of https://github.com/melisgl/named-readtables/issues/19, since fixed in SBCL. Closing.

**Closed as completed by melisgl** 2020-07-28 07:30 UTC
